/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Inicio;
import Modelo.CLIENTE;
import Modelo.CONSULTAS;
import Modelo.FACTURA;
import Modelo.SERVICIO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class PANTALLABASE extends javax.swing.JFrame {

    /**
     * Creates new form PANTALLABASE
     */
    private Point puntoInicial;
    private CONSULTAS Consulta;
    private SERVICIO Servicio;
    private LinkedList<FACTURA> Facturas;
    private Timer t;
    private Calendar c;
    private String h;

    public PANTALLABASE(String username, String img) {
        initComponents();
        miconfiguracion(username, img);
    }

    private void miconfiguracion(String username, String img) {
        this.setLocationRelativeTo(null);
        this.Consulta = new CONSULTAS(username);
        this.Servicio = new SERVICIO();
        this.setSize(500, 300);
        Facturas = new LinkedList();
        this.JLUSER.setText(username);

        t = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int hora, minutos, segundos;
                c = Calendar.getInstance();
                hora = c.get(Calendar.HOUR_OF_DAY);
                minutos = c.get(Calendar.MINUTE);
                segundos = c.get(Calendar.SECOND);
                h = hora + ":" + minutos + ":" + segundos;
                JLHORA.setText(h);
            }
        });

        t.start();

        ImageIcon ic = new javax.swing.ImageIcon(getClass().getResource(Inicio.getImg()));
        Icon i = new javax.swing.ImageIcon(ic.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));

        JLIMGUSER.setIcon(i);

        setTexto();
    }

    private void setTexto() {
        obtenerServicio();
        obtenerFacturas();
    }

    private void obtenerServicio() {

        Servicio = (SERVICIO) Inicio.realizarConsulta(null, CONSULTAS.TABLAS.SERVICIO.ordinal(), false);
        JLSERVICIO.setText(Servicio.getDESCRIPCION());

    }

    private void obtenerServicioSiguienteAnterior(boolean b) { // true si hacia adelante, false si hacia atrás
        if (b) {
            Servicio = (SERVICIO) Inicio.realizarConsulta("next", CONSULTAS.TABLAS.SERVICIO.ordinal(), false);
        } else {
            Servicio = (SERVICIO) Inicio.realizarConsulta("prev", CONSULTAS.TABLAS.SERVICIO.ordinal(), false);
        }

        JLSERVICIO.setText(Servicio.getDESCRIPCION());

    }

    private void obtenerFacturas() {

        try {

            FACTURA fac = new FACTURA();
            CLIENTE cli = new CLIENTE();

            DefaultTableModel modelo = (DefaultTableModel) JTFACTURAS.getModel(); // creamos un modelo de tabla donde insertar los registros, metiendo el diseño que teniamos antes

            modelo.setRowCount(0); // LIMPIAMOS TODAS LAS FILAS

            Facturas = (LinkedList) Inicio.realizarConsulta(Consulta.verC(Servicio.getCOD()), CONSULTAS.TABLAS.FACTURA.ordinal(), true);

            for (int a = 0; a < Facturas.size(); a++) {
                fac = (FACTURA) Facturas.get(a);

                cli = (CLIENTE) Inicio.realizarConsulta(Consulta.verClienteDeFactura(fac.getCOD_CLIENTE()), CONSULTAS.TABLAS.CLIENTE.ordinal(), false);

                modelo.addRow(new Object[1]); // CREAMOS UNA NUEVA FILA DONDE INSERTAR LOS DATOS
                modelo.setValueAt(cli.getNOMBRE(), a, 0);
                modelo.setValueAt(fac.getDESCRIPCION(), a, 1);
                modelo.setValueAt(fac.getPRECIO(), a, 2);

            }

            JTFACTURAS.setModel(modelo);
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JBSALIR = new javax.swing.JButton();
        JLUSER = new javax.swing.JLabel();
        JLIMGUSER = new javax.swing.JLabel();
        JLHORA = new javax.swing.JLabel();
        JBSESION = new javax.swing.JButton();
        JBINFO = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JLSERVICIO = new javax.swing.JLabel();
        JBNEXT = new javax.swing.JButton();
        JBPREV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTFACTURAS = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        JBSALIR.setBackground(java.awt.Color.GRAY);
        JBSALIR.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        JBSALIR.setForeground(new java.awt.Color(204, 204, 204));
        JBSALIR.setText("X");
        JBSALIR.setBorderPainted(false);
        JBSALIR.setContentAreaFilled(false);
        JBSALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBSALIR.setFocusPainted(false);
        JBSALIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBSALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBSALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBSALIRMouseExited(evt);
            }
        });
        JBSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSALIRActionPerformed(evt);
            }
        });

        JLUSER.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JLUSER.setForeground(new java.awt.Color(255, 255, 255));
        JLUSER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLUSER.setText("USUARIO");
        JLUSER.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLIMGUSER.setBackground(new java.awt.Color(255, 255, 255));
        JLIMGUSER.setForeground(new java.awt.Color(255, 255, 255));
        JLIMGUSER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLIMGUSER.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLIMGUSER.setMaximumSize(new java.awt.Dimension(30, 30));
        JLIMGUSER.setMinimumSize(new java.awt.Dimension(30, 30));
        JLIMGUSER.setPreferredSize(new java.awt.Dimension(30, 30));

        JLHORA.setForeground(new java.awt.Color(255, 255, 255));
        JLHORA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHORA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JBSESION.setBackground(java.awt.Color.GRAY);
        JBSESION.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        JBSESION.setForeground(new java.awt.Color(204, 204, 204));
        JBSESION.setText("X");
        JBSESION.setBorderPainted(false);
        JBSESION.setContentAreaFilled(false);
        JBSESION.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBSESION.setFocusPainted(false);
        JBSESION.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBSESION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBSESIONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBSESIONMouseExited(evt);
            }
        });
        JBSESION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSESIONActionPerformed(evt);
            }
        });

        JBINFO.setBackground(java.awt.Color.GRAY);
        JBINFO.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        JBINFO.setForeground(new java.awt.Color(204, 204, 204));
        JBINFO.setText("i");
        JBINFO.setBorderPainted(false);
        JBINFO.setContentAreaFilled(false);
        JBINFO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBINFO.setFocusPainted(false);
        JBINFO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBINFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBINFOMouseExited(evt);
            }
        });
        JBINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBINFOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLIMGUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLUSER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLHORA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(JBINFO)
                .addGap(0, 0, 0)
                .addComponent(JBSESION)
                .addGap(0, 0, 0)
                .addComponent(JBSALIR))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JLHORA, JLUSER});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBSALIR)
                        .addComponent(JBSESION)
                        .addComponent(JBINFO))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JLIMGUSER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLHORA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLUSER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLSERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLSERVICIO.setText("SERVICIO");

        JBNEXT.setText("NEXT");
        JBNEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNEXTActionPerformed(evt);
            }
        });

        JBPREV.setText("PREV");
        JBPREV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPREVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBPREV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLSERVICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBNEXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLSERVICIO)
                    .addComponent(JBNEXT)
                    .addComponent(JBPREV))
                .addContainerGap())
        );

        JTFACTURAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTFACTURAS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        JTFACTURAS.setEnabled(false);
        jScrollPane1.setViewportView(JTFACTURAS);
        if (JTFACTURAS.getColumnModel().getColumnCount() > 0) {
            JTFACTURAS.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jButton2.setText("crear Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("crear Servicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation((int) (evt.getXOnScreen() - puntoInicial.getX()), (int) (evt.getYOnScreen() - puntoInicial.getY()));
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        puntoInicial = new Point(evt.getXOnScreen() - this.getX(), evt.getYOnScreen() - this.getY());
    }//GEN-LAST:event_formMousePressed

    private void JBSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSALIRActionPerformed
        Inicio.cerrarConexion();
        t.stop();
        System.exit(0);
    }//GEN-LAST:event_JBSALIRActionPerformed

    private void JBSALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSALIRMouseEntered
        JBSALIR.setForeground(Color.RED);
    }//GEN-LAST:event_JBSALIRMouseEntered

    private void JBSALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSALIRMouseExited
        JBSALIR.setForeground(Color.GRAY);
    }//GEN-LAST:event_JBSALIRMouseExited

    private void JBPREVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPREVActionPerformed
        obtenerServicioSiguienteAnterior(false);
        obtenerFacturas();
    }//GEN-LAST:event_JBPREVActionPerformed

    private void JBNEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNEXTActionPerformed
        obtenerServicioSiguienteAnterior(true);
        obtenerFacturas();
    }//GEN-LAST:event_JBNEXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NUEVOSERVICIO dialog = new NUEVOSERVICIO(new javax.swing.JFrame(), true, Inicio.getUser(), Inicio.getImg());
                
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NUEVAFACTURA dialog = new NUEVAFACTURA(new javax.swing.JFrame(), true, Servicio);
                
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JBSESIONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSESIONMouseEntered
        JBSESION.setForeground(Color.WHITE);
    }//GEN-LAST:event_JBSESIONMouseEntered

    private void JBSESIONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSESIONMouseExited
        JBSESION.setForeground(Color.GRAY);
    }//GEN-LAST:event_JBSESIONMouseExited

    private void JBSESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSESIONActionPerformed
        Inicio.cerrarConexion();
        this.dispose();
        Inicio.login();
    }//GEN-LAST:event_JBSESIONActionPerformed

    private void JBINFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBINFOMouseEntered
        JBINFO.setForeground(Color.WHITE);
    }//GEN-LAST:event_JBINFOMouseEntered

    private void JBINFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBINFOMouseExited
        JBINFO.setForeground(Color.GRAY);
    }//GEN-LAST:event_JBINFOMouseExited

    private void JBINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBINFOActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ACERCADE dialog = new ACERCADE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_JBINFOActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBINFO;
    private javax.swing.JButton JBNEXT;
    private javax.swing.JButton JBPREV;
    private javax.swing.JButton JBSALIR;
    private javax.swing.JButton JBSESION;
    private javax.swing.JLabel JLHORA;
    private javax.swing.JLabel JLIMGUSER;
    private javax.swing.JLabel JLSERVICIO;
    private javax.swing.JLabel JLUSER;
    private javax.swing.JTable JTFACTURAS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
